services:
  - type: web
    name: youtube-downloader
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app.py"
    envVars:
      - key: FLASK_ENV
        value: production
