services:
  - type: web
    name: youtube-downloader
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn main:app"
    envVars:
      - key: PORT
        value: 10000
      - key: FLASK_ENV
        value: production
